### ISSUE TITLE
下書き機能

### ISSUE THREAD

**Issue by ko-he-** [koga-yatsushiro/one_month#2]
質問がQuestion.draftで下書きかどうかを判定でき、また、チェックボックスもあるが機能していない。

**Comment by ko-he-** [comment]
dotchain/q_edit/質問idで編集画面に飛べる。
（2015/7/3現在リンクははっていない）

**Comment by ykoga-kyutech** [comment]
下書き機能実装しました。下書きの質問は自分のみ、自分の投稿、すべての質問で閲覧・編集することができます。
