### ISSUE TITLE
トップ画面で　”Uncaught Error: Syntax error, unrecognized expression: .###”というエラーが出る

### ISSUE THREAD

**Issue by ykoga-kyutech** [koga-yatsushiro/one_month#33]
トップ画面をデベロッパーツールで見ると、タイトルのようなエラーをはいている。
これは使うかと思って残しておいたコードがそのままになっているため。

one_month/static/js/top.js　の、10～29行目を削除すればなおる。

**Comment by sakaro01** [comment]
10~29行目を削除しておきました。
