### ISSUE TITLE
新規登録後すぐに質問しようとするとエラーになる。

### ISSUE THREAD

**Issue by ko-he-** [koga-yatsushiro/one_month#57]
新規登録後、プロフィールが作成されないため質問の作成などを行うとエラーとなる。
プロフィールを設定していないユーザを弾くか、
自動でデフォルトのプロフィールをつける必要がある。

**Comment by ykoga-kyutech** [comment]
one_month/init_application.pyのstart_up()内にユーザのプロフィールが作成されていなければ作成するようにしました。
ほかに初期化処理がしたかったらこの中ですればいいです。
